### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by wangzimei** [nebulasio/web-wallet#31]
replace \="([^ =]+)" with =$1

sendNas.html/onClickSendTransaction 最后那 ajax 为啥要等 1 分钟? - otto

http://34.205.26.12:8685/
https://testnet.nebulas.io/
https://github.com/nebulasio/wiki/blob/master/rpc.md

2018.3.19 ~ 2018.3.24
- 主网测试网络切换
- 多语言
- 查询帐号余额 - View Wallet Info 页面有
- 根据交易 hash 查询交易信息（如果交易执行失败，需要提示失败和错误类型）
- 部署和执行合约（JS）

删除 js/Blob.js
删除 js/nebulas.js

**Comment by ChengOrangeJu** [comment]
Issue fixed
