### ISSUE TITLE
发现一个钱包的bug。

### ISSUE THREAD

**Issue by wmaster** [nebulasio/web-wallet#36]
查看钱包信息时，输入完地址和密码后，连续点击“解锁”按钮，下面的二维码地址会重复append，而不是进行replace。

**Comment by 15010159959** [comment]
ok,的确是 append的 bug问题 ，我会及时修改。 谢谢👍

**Comment by fzxa** [comment]
已经加入todo list

**Comment by fzxa** [comment]
问题已修复
