### ISSUE TITLE
无法连接本地节点

### ISSUE THREAD

**Issue by DanisFabric** [nebulasio/web-wallet#37]
本地节点使用默认的config已经在运行。用curl读取http://localhost:8685/v1/user/accountstate 接口能够拿到对应的账户信息。

但是我用web钱包，然后选择local nodes。读取钱包信息或者其他操作，都会弹“网络错误”的提示框。

是为什么呀

**Comment by 15010159959** [comment]
你的本地节点是保持打开的，我尝试过，只有本地节点关闭了才会出现 '网络错误' 的情况

**Comment by DanisFabric** [comment]
我打开本地节点
![2018-05-02 3 57 32](https://user-images.githubusercontent.com/7201854/39511875-8f4ed0de-4e21-11e8-9399-99b9f58e2758.png)
用postman获取账户信息没问题
<img width="582" alt="2018-05-02 3 58 34" src="https://user-images.githubusercontent.com/7201854/39511954-c1b6f6dc-4e21-11e8-8ccc-463b62154e23.png">
但是web-wallet就是会报错
<img width="1311" alt="2018-05-02 3 59 42" src="https://user-images.githubusercontent.com/7201854/39511998-f50cf694-4e21-11e8-9e43-027276fea65b.png">
