### ISSUE TITLE
testnet 执行函数参数错误

### ISSUE THREAD

**Issue by DanisFabric** [nebulasio/web-wallet#38]
合约里面两个函数
```
    registerUser(name) {
        let realName: string;
        if (!name || name.trim() === "") {
            realName = name;
        }  else {
            realName = "Danis";
        }
        this.users.set(Blockchain.transaction.from, realName);
    }

    test() {
        return "Call Test Function Succeed";
    }
```

我部署合约到testnet，然后用web-wallet调用函数`test()`没有问题。
![2018-05-04 3 17 56](https://user-images.githubusercontent.com/7201854/39616597-d63758d4-4fae-11e8-9567-a014c15476a4.png)
但是我调用需要传入参数的`registerUser()`就遇到了问题。
我不传入参数，那么报错"value must be string"。
![2018-05-04 3 18 20](https://user-images.githubusercontent.com/7201854/39616613-ec7b1586-4fae-11e8-9e28-ac408b6ea768.png)
但是我在参数填入`"Jack"`，输出则为空的花括号。
![2018-05-04 3 18 36](https://user-images.githubusercontent.com/7201854/39616660-20eea2c4-4faf-11e8-927e-26ce80df8c7a.png)

**Comment by ChengOrangeJu** [comment]
@DanisFabric Looking into your issue, stay tuned :)

**Comment by ChengOrangeJu** [comment]
@DanisFabric Please use ["jack"] as the input.  (you can click the ? for reference).
We will further improve the use experience in the near future.

**Comment by DanisFabric** [comment]
It works, thanks a lot
