### ISSUE TITLE
这钱包不需要同步区块？？？

### ISSUE THREAD

**Issue by lancesf** [nebulasio/web-wallet#40]
就一个web项目？？？直接打开index.html使用？？ 创建了钱包账号，拿账号地址上你们官网https://explorer.nebulas.io/#/查，也查不到。。逗我们玩阿？？

**Comment by lancesf** [comment]
打开F12控制台，报个webExtensionWallet is defined:for nebulas，也莫名其妙，都装了google插件webExtensionWallet 了，重新启动也还这样。。我都能在这个插件上导入钱包文件输入密码解锁

**Comment by ChengOrangeJu** [comment]
@lancesf You could select the right network to check which your account locates

**Comment by yupnano** [comment]
“webExtensionWallet is defined:for nebulas”是插件打印的log信息，每打开一个页面都会有这个log，这不是错误。正是因为你装了插件才会打印的。

**Comment by yupnano** [comment]
“webExtensionWallet is defined:for nebulas”是插件打印的log信息，每打开一个页面都会有这个log，这不是错误。正是因为你装了插件才会打印的。

**Comment by lancesf** [comment]
说了跟没说一样
