### ISSUE TITLE
web钱包发送交易时报400错误

### ISSUE THREAD

**Issue by Jaylin-LoVe** [nebulasio/web-wallet#41]
发送2个NAS, GAS限制和GAS价格都改为1

![1](https://user-images.githubusercontent.com/20453450/39693514-d293135c-5216-11e8-8335-332b7807e828.png)

![3](https://user-images.githubusercontent.com/20453450/39693516-d5e2fb4e-5216-11e8-8612-335d026e3a32.png)

**Comment by ChengOrangeJu** [comment]
hello @Jaylin-LoVe the gasprice and gas limit is too small to be packaged.
gasprice should >= 1000000and gaslimit should > 20000.

**Comment by Jaylin-LoVe** [comment]
Alright ,  It would be better if give an error description , rather than showing an unknown error. O(∩_∩)O
