### ISSUE TITLE
连接本地网络报错

### ISSUE THREAD

**Issue by duanyuGit** [nebulasio/web-wallet#43]
为什么连接本地网络导入钱包文件后，点击解锁，老是报{error: "Method Not Allowed"}
错误呢，测试网络和主网没问题
<img width="477" alt="fc4ab7ca-3316-49ae-acc5-d43fe6d9509f" src="https://user-images.githubusercontent.com/5362081/39733653-4cc7e83e-52a6-11e8-8d0b-4a963fa0746b.png">

**Comment by ChengOrangeJu** [comment]
hello @duanyuGit please check https://github.com/nebulasio/wiki/issues/111
