### ISSUE TITLE
Creating new wallet does not accept password setup (over 9 characters)

### ISSUE THREAD

**Issue by jkreesejr** [nebulasio/web-wallet#45]
First step in creating a new wallet does not accept password (over 9 digits) and does nothing.  I'm using Chrome and have tried others.  Others on YouTube viewing PART 1 are commenting that they have this same issue trying to create a new wallet

**Comment by KEMiCZA** [comment]
I couldn't reproduce this bug. Tried both on master and develop branch using chrome and IE. Both generate a wallet (mainnet and testnet). Could you be more specific with the steps you did?

**Comment by jkreesejr** [comment]
Followed same steps on my iMac and loaded OK, so I will use that.  The problem seems to be a problem with my Windows 10 64 bit laptop (Lenovo Thinkpad).  I used the .zip files vs terminal in both cases.
