### ISSUE TITLE
deploy contract got 400 error code.

### ISSUE THREAD

**Issue by zslucky** [nebulasio/web-wallet#46]
After test, I submit the contract, but got 400 error.

![image](https://user-images.githubusercontent.com/15725589/39901836-82208712-54fd-11e8-9ff0-0545bd00ad15.png)

**Comment by smartpunter** [comment]
It means that your contract source has some errors.
Try to run your contract with node.js and see what errors you have, usually it is just some misprints.

But wallet should notify user about this, not just silently abort transaction.

**Comment by zslucky** [comment]
thanks @smartpunter , may not source errors, testing told me `insufficient balance`, is that mean I should paid gas for deploying? Or I think it should give me a friendly error message.

**Comment by smartpunter** [comment]
Ah yeah, definitely, you need to have some NAS on your account.
1 NAS will be enough for roughly 30 000 000 transactions.
Do the math, how much should you spend :)

**Comment by zslucky** [comment]
@smartpunter thanks , I see, but I still think we should have a friendly error message 😄
