### ISSUE TITLE
太low了，随手搞个web项目就当钱包，还一堆bug，文档也渣，就那么几句话介绍

### ISSUE THREAD

**Issue by lancesf** [nebulasio/web-wallet#48]
这还什么星云链悬赏计划，什么每周每月几万十几万几十万的什么开发者大奖。。忽悠谁呢？有这么多资金，喜欢砸到推广里，技术开发就这成果？？团队没水平还是开发人手不够？还是资金放悬赏计划里了，没资金招？？

**Comment by ChengOrangeJu** [comment]
@lancesf 激励计划请敬请期待开奖结果。
技术细节请深度研究go-nebulas。
web上的简陋是出于人手所限，一定会越来越好。
如果社区贡献更好的产品和工具，星云也一定会有奖励给您：）
如果有更多的问题请添加微信nebulasio，申请加入技术群。谢谢您对项目的关心
