### ISSUE TITLE
Viewing in web-wallet shows 0 NAS, in NAS nano I see 3000 NAS

### ISSUE THREAD

**Issue by owenbirdsall** [nebulasio/web-wallet#63]
After importing my web wallet into the NAS Nano iOS app, it now shows 0 NAS when I view it with the web wallet. If I look on explorer.nebulas it shows 3000 NAS... so it seems just the web wallet is incorrect

**Comment by gplibs** [comment]
@owenbirdsall 
Are you choosing the wrong network?
For example, there is a balance on the Mainnet, but the wallet has chosen Testnet.

**Comment by owenbirdsall** [comment]
@gplibs Yes, you're right ...sorry, I'd completely missed that - in my defence the main/testnet text is very faint :)
